---
- name: Create Resource Group
  hosts: localhost  
  gather_facts: no

  tasks:

    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ region }}"
        state: present