- name: Create NAT Gateway
  hosts: nat
  connection: local
  gather_facts: no

  tasks:

    - name: Create Private DNS Zone
      azure.azcollection.azure_rm_privatednszone:
        resource_group: "{{ resource_group }}"
        name: "{{ zone_name }}"

    - name: Create DNS Records
      azure.azcollection.azure_rm_privatednsrecordset:
        resource_group: "{{ resource_group }}"
        zone_name: "{{ zone_name }}"
        relative_name: "{{ item.name }}"
        record_type: "{{ item.type }}"
        records: "{{ item.records }}"
      with_items: "{{ dns_records }}"